In [1]:
a=12
# numpy is written is c language which are compiled and super fast 


In [2]:
print("hello")

hello


In [3]:
def hello():
    print("hello how  are u")

In [4]:
hello()



hello how  are u


In [5]:
#numpy is written in c 


In [6]:
# numpy Arrays,numpy indexing, numpy operations, numpy exercise

In [3]:
import numpy as np

In [4]:
# basic array creation

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a=[1,2,3,"array"]
a

[1, 2, 3, 'array']

In [7]:
np.array(a)

array(['1', '2', '3', 'array'], dtype='<U11')

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#array generation funtion


In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [19]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [20]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [21]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [23]:
#random number generation

In [25]:
# normalisation 0-1
np.random.rand(10)

array([0.61660177, 0.7699716 , 0.40004396, 0.48700585, 0.43865828,
       0.53673966, 0.57342087, 0.59998495, 0.93575636, 0.24648248])

In [26]:
# standrazation -3--3
np.random.randn(10)

array([ 0.31581308, -1.02165131, -0.0362055 ,  0.06156979, -1.8997012 ,
        1.48074134,  0.62448185,  1.84417837, -0.62392957, -2.1528306 ])

In [29]:
np.random.randint(6)

1

In [30]:
np.random.randint(10,20,10)

array([14, 15, 14, 18, 19, 12, 10, 14, 14, 16])

In [31]:
# array attributes

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr          

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape #attributes

(3, 3)

In [35]:
arr.size #attributes

9

In [36]:
arr.dtype #attributes

dtype('int32')

In [37]:

# Array method

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.min()

1

In [40]:
arr.max()

9

In [41]:
arr.sum()

45

In [42]:
np.sum(arr,axis = 0) #column wise 

array([12, 15, 18])

In [43]:
np.sum(arr,axis =1) #row wise 

array([ 6, 15, 24])

In [44]:
arr.mean()

5.0

In [45]:
arr.std()

2.581988897471611

In [46]:
arr.argmax()

8

In [47]:
arr.argmin()

0

In [48]:
# Reshaping and resizing 

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
# advance concept

In [55]:
import numpy as np


In [56]:
# numpy indexing and slicing of vector

In [60]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
arr[6]

17

In [62]:
arr[9]

20

In [63]:
arr[1:5]

array([12, 13, 14, 15])

In [64]:
arr[:5] # default start is 0

array([11, 12, 13, 14, 15])

In [65]:
arr[:] # whole arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [66]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [67]:
arr[3::2] #2 is step

array([14, 16, 18, 20])

In [68]:
arr[4]

15

In [69]:
# numpy indexing and slicing of matrix

In [71]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [72]:
arr[0]

array([1, 2, 3, 4, 5])

In [73]:
arr[5]

array([26, 27, 28, 29, 30])

In [74]:
arr[0][0]

1

In [75]:
arr[0,0]

1

In [76]:
arr[0,4]

5

In [77]:
arr[5,4]

30

In [78]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [80]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [83]:
slice1 = arr[3:,3:]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [84]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [86]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [88]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [89]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [90]:
# Array operations

In [93]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [96]:
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

In [98]:
sub = a1-a2
sub

array([-5, -5, -5, -5, -5])

In [99]:
mul  = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [100]:
div = a1 /a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [102]:
florDiv = a1 // a2
florDiv

array([0, 0, 0, 0, 0])

In [105]:
expo = a1 ** a2
expo

array([      1,     128,    6561,  262144, 9765625])

In [106]:
# Broadcasting

In [108]:
l = [10,20,30,40]
arr = np.array(l)

In [109]:
arr +10

array([20, 30, 40, 50])

In [110]:
arr2 = np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [112]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [113]:
# deep and shallow copy

In [119]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [120]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [121]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [122]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [123]:
a[4:6]*10

array([50, 60])

In [124]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
a
b=a

In [126]:
b[0]=99


In [127]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [128]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [129]:
a
b=a.copy()

In [130]:
b[0] = 100

In [131]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [132]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [138]:
# matrix operations
A= np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [135]:
A

array([[1, 2],
       [3, 4]])

In [136]:
B

array([[5, 6],
       [7, 8]])

In [137]:
A*B

array([[ 5, 12],
       [21, 32]])

In [139]:
A@B

array([[19, 22],
       [43, 50]])

In [140]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [141]:
A.T

array([[1, 3],
       [2, 4]])

In [142]:
# Advance array manipulation

In [143]:
A

array([[1, 2],
       [3, 4]])

In [144]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# Stacking Array

In [ ]:
A= np.array([1,2,3,4])
B = np.array([5,6,7,8])

In [145]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [148]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [149]:
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [150]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [152]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [156]:
a=np.vsplit(c,4)

In [157]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [158]:
# Excerises

In [159]:
# Valid Sudoku

In [165]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [167]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [170]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [174]:
b=np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("suduko is not valid")
        break
    else:
        print("for rows it is valid")

for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid


In [177]:
c=np.sum(s,axis=1)
for i in c:
    if i != 45:
        print("suduko is not valid")
        break
    else:
        print("for columns it is valid")

for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid


In [178]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [179]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [180]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [182]:

for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [168]:
# General Questions

In [184]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [185]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [186]:
#Find the average age of students.
np.mean(data[:,0])

18.4

In [187]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [189]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [192]:
#Get details of the student who scored more than 90 in Math.
data [data[:,1]>90]

array([[19, 92, 88]])

In [197]:
#Increase Math marks of all students by 5.
# data
data[:,1]+=5
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [200]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [203]:
#Calculate the average marks in each subject (column-wise mean).

np.mean(data[:,1:],axis =0)

array([96.6, 83.2])

In [204]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[ 19, 107,  88],
       [ 17,  91,  95],
       [ 20, 105,  85]])

In [206]:
#Replace all Science marks < 75 with 0.
data


array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [211]:
data[:,2][data[:,2] < 75] = 0
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [  0,   0,   0],
       [ 20, 105,  85]])

In [3]:
import numpy as np

In [5]:
arr = np.arange(1,11,2)
arr



array([1, 3, 5, 7, 9])

In [6]:
arr = np.zeros(6)
arr


array([0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros((4,8))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [ ]:
# random number genration function